### ISSUE TITLE
MacOs Version

### ISSUE THREAD

**Issue by vjsantojaca** [tishige/CallFlowVisualizer#1]
Hi, I want to know if exist any option to run this program on MacOs. I see that in the code exist some logic about Mac OSX but I don't know how should i compile it.

Thanks and best regards!

**Comment by tishige** [comment]
Ok, I will release the MacOS version again. I'll let you know once it's done.

**Comment by tishige** [comment]
Hi
You can download v1.6.1 for mac.
Thanks
Ishi

**Comment by tishige** [comment]
Released CallFlowVisualizer-Mac-1.6.1.zip
https://github.com/tishige/CallFlowVisualizer/releases/download/1.6.1/CallFlowVisualizer-Mac-1.6.1.zip
