### ISSUE TITLE
Not producing any Drawing or image files

### ISSUE THREAD

**Issue by srlandon** [tishige/CallFlowVisualizer#2]
I see there is a note in the ReadMe. 

Are there any plans to get this working again?

**Comment by tishige** [comment]
Hi
Sorry for late reply.
What architect flow can't you get?
Please refer to 
https://community.genesys.com/discussion/creates-flowcharts-of-genesys-cloud-or-pureconnect-interaction-flow
as well
Ishi

**Comment by tishige** [comment]
Hi, Try to use the latest version.
Let me know the result in Genesys community thread if the issue still exists.
Ishi
